crops:
  wheat:
    average: 1
  wheat_seeds:
    average: 1.4
    min: 0
    max: 2
  carrot:
    average: 1.75
    min: 0
    max: 3
  potato:
    average: 1.6
    min: 0
    max: 3
  melon_slice:
    average: 1.6
    min: 1
    max: 5
  beetroot:
    average: 2.66
    min: 1
    max: 4
  beetroot_seeds:
    average: 1.4
    min: 0
    max: 2
bonemeal:
  reduce:
    - wheat
    - carrots
    - potatoes
    - melon_stem
    - pumpkin_stem
    - beetroots
  average: 1.4
  beetroot_factor: 0.35
fish:
  cod: 0.75
  salmon: 0.3
  tropical_fish: 0.1
  pufferfish: 0.01